name: Java CI with Maven

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    
    - name: clean
      run: mvn clean
    
    - name: Build with Maven
      run: | 
        mvn -B package --file my-app/pom.xml
        tree
        pwd
