name: my workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: |
        v=1.2.2
        echo "GITHUB_SHA_SHORT=$v" >> $GITHUB_ENV
    - name: Test
      run: echo $GITHUB_SHA_SHORT
